
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CREDISYS
{

using System;
    using System.Collections.Generic;
    
public partial class Domicilio
{

    public int idDomicilio { get; set; }

    public string colonia { get; set; }

    public string codPostal { get; set; }

    public string numIn { get; set; }

    public string numExt { get; set; }

    public string calle { get; set; }

    public int idCiudad { get; set; }

    public int idEstado { get; set; }

    public int idPais { get; set; }

    public string tiempoResidencia { get; set; }

    public int idTipoDomicilio { get; set; }

    public string rfcCliente { get; set; }

    public string estatus { get; set; }



    public virtual Ciudad Ciudad { get; set; }

    public virtual Cliente Cliente { get; set; }

    public virtual Estado Estado { get; set; }

    public virtual Pai Pai { get; set; }

    public virtual TipoDomicilio TipoDomicilio { get; set; }

}

}
