insert into dbo.Estado (estado, estatus, idPais) values ('Veracruz','activo',1)
insert into dbo.Estado (estado, estatus, idPais) values ('Sinaloa','activo',1)
insert into dbo.Estado (estado, estatus, idPais) values ('Oaxaca','activo',1)
insert into dbo.Estado (estado, estatus, idPais) values ('Nuevo León','activo',1)
insert into dbo.Ciudad (ciudad, idEstado, estatus) values ('Xalapa',1,'activo')
insert into dbo.Ciudad (ciudad, idEstado, estatus) values ('Culiacán',2,'activo')
insert into dbo.Ciudad (ciudad, idEstado, estatus) values ('Oaxaca',3,'activo')
insert into dbo.Ciudad (ciudad, idEstado, estatus) values ('Monterrey',4,'activo')
insert into dbo.TipoDomicilio (estatus,	tipoDomicilio) values ('activo','propietario')
insert into dbo.TipoDomicilio (estatus,	tipoDomicilio) values ('activo','hipotecado')
insert into dbo.TipoDomicilio (estatus,	tipoDomicilio) values ('activo','alquiler')
insert into dbo.TipoDomicilio (estatus,	tipoDomicilio) values ('activo','familiar')
insert into dbo.TipoDomicilio (estatus,	tipoDomicilio) values ('activo','otro')
insert into dbo.CondicionCredito (condicion, interes, iva, estatus) values ('tasa cero',0,16,'activo')
insert into dbo.CondicionCredito (condicion, interes, iva, estatus) values ('tasa cinco',5,16,'activo')
insert into dbo.Banco (banco, estatus) values ('BBVA','activo')
insert into dbo.Banco (banco, estatus) values ('Banorte','activo')
insert into dbo.Banco (banco, estatus) values ('HSBC','activo')
insert into dbo.Banco (banco, estatus) values ('Santander', 'activo')